-- 코드를 입력하세요
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM (SELECT *, RANK() OVER(PARTITION BY FOOD_TYPE ORDER BY FOOD_TYPE, FAVORITES DESC) AS RNK
     FROM REST_INFO) AS REST
WHERE REST.RNK <= 1
ORDER BY FOOD_TYPE DESC